# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 29, 14, 11, 13, 325942, tzinfo=utc)),
        ),
    ]
